# Copyright (c) 2023 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.  


title: "OCI Networking Module OCI ORM Stack"
stackDescription: "Creates or changes any networking resource in any configuration in OCI."
description: "Creates or changes any networking resource in any configuration in OCI."
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

# URL of CIS Landing Zone logo icon used on Application Information tab.
logoUrl: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/taf6kC9fSJyQDNSYbxvqxS_JsdnSu56oFZ3-1h5vI7-WfJUv77mplChopLxZPePW/n/ociateam/b/cis-landing-zone/o/landing_zone_130.png"

variableGroups:
  - title: "INPUT JSON OR YAML NETWORKING CONFIGURATION FILE URL"
    visible: true
    variables:
      - default_compartment_ocid
      - input_config_file_url
  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"
      - "region"
      - "home_region"
variables:
  default_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Default compartment OCID"
    description: "The compartment that will be used by default by all the networking resources if no specific network resource or category compartments are defined."
    required: false 
    visible: true

  input_config_file_url:
    type: string
    title: Type or Paste the URLs
    additionalProps:
        allowMultiple: true
    description: "Only JSON OR YAML file accepted - HCL not supported yet"
    required: false

outputs:
  release:
    type: string
    title: OCI Open Landing Zone Networking Module

  region:
    type: string
    title: Region

  provisioned_networking_resources:
    type: json
    title: Provisioned Networking Resources 

outputGroups:
  - title: Environment
    outputs:
      - ${release}
      - ${region}

  - title: Networking Resources
    outputs:
      - ${provisioned_networking_resources}    