# ####################################################################################################### #
# Copyright (c) 2023 Oracle and/or its affiliates,  All rights reserved.                                  #
# Licensed under the Universal Permissive License v 1.0 as shown at https: //oss.oracle.com/licenses/upl. #
# Author: Cosmin Tudor                                                                                    #
# Author email: cosmin.tudor@oracle.com                                                                   #
# Last Modified: Tue Nov 21 2023                                                                          #
# Modified by: Cosmin Tudor, email: cosmin.tudor@oracle.com                                               #
# ####################################################################################################### #

---
network_configuration:
  default_enable_cis_checks: false
  default_freeform_tags:
    vision-environment: vision
  network_configuration_categories:
    HUB:
      category_freeform_tags:
        vision-sub-environment: hub
      non_vcn_specific_gateways:
        dynamic_routing_gateways:
          DRG-HUB-KEY:
            display_name: drg-hub
            drg_attachments:
              DRG-HUB-VCN-A-ATTACH-KEY:
                display_name: drg-hub-vcn-a-attach
                # Ingress Routes table - entering DRG through DRG-A-VCN-A
                drg_route_table_key: DRG-RT-SPOKE-KEY
                network_details:
                  attached_resource_key: VCN-A-KEY
                  type: VCN
              DRG-HUB-VCN-B-ATTACH-KEY:
                display_name: drg-hub-vcn-b-attach
                # Ingress Routes table - entering DRG through DRG-A-VCN-B
                drg_route_table_key: DRG-RT-SPOKE-KEY
                network_details:
                  attached_resource_key: VCN-B-KEY
                  type: VCN
              DRG-HUB-VCN-C-ATTACH-KEY:
                display_name: drg-hub-vcn-c-attach
                # Ingress Routes table - entering DRG through DRG-A-VCN-C
                drg_route_table_key: DRG-RT-SPOKE-KEY
                network_details:
                  attached_resource_key: VCN-C-KEY
                  type: VCN
              DRG-HUB-VCN-H-ATTACH-KEY:
                display_name: drg-hub-vcn-h-attach
                # Ingress Routes table - entering DRG through DRG-A-VCN-HUB
                # drg_route_table_key: DRG-RT-HUB-KEY
                network_details:
                  attached_resource_key: VCN-HUB-KEY
                  # Egress Routes table - from DRGA-VCN-HUB to HUB-VCN
                  # Route traffic than enters HUB VCN to the NFW
                  route_table_key: VCN-H-INGRESS-RT-KEY
                  type: VCN
            drg_route_tables:
              # Callout 2
              # Ingress Routes table - entering DRG through DRG-A-VCN-HUB
              # This should be BGP - dynamic routing
              # The creation of dynamic routing is not supported yet by this automation
              # On the roadmap there are plans to add support for: DrgRouteDistribution and DrgRouteDistributionStatements
              DRG-RT-HUB-KEY:
                display_name: drg-rt-hub
                is_ecmp_enabled: false
                # All the bellow route rules should be dynamic and not static - they should be created as means of BGP discovery and DrgRouteDistribution/DrgRouteDistributionStatements
                # For now you'll need to manually create the bellow route rules after this configuration is provisioned by terraform.
                route_rules: null
              # Callout 1
              # DRG ingress - from DRG-Attachments to DRG
              # Attached to the DRG Attachments - expect the HUB-VCN DRG-Attachment
              # Sending all default traffic to the HUB VCN via the DRG-Attachment
              DRG-RT-SPOKE-KEY:
                display_name: drg-rt-spoke
                is_ecmp_enabled: false
                route_rules:
                  ALL-TRAFFIC-FROM-SPOKES-TO-HUB-KEY:
                    destination: 0.0.0.0/0
                    destination_type: CIDR_BLOCK
                    next_hop_drg_attachment_key: DRG-HUB-VCN-H-ATTACH-KEY
        fast_connect_virtual_circuits:
          VISON-FC-VC-1-KEY:
            bandwidth_shape_name: 1 Gbps
            cross_connect_mappings:
              MAPPING-1-KEY:
                customer_bgp_peering_ip: 172.168.3.1/30
                oracle_bgp_peering_ip: 172.168.3.2/30
            customer_asn: '65000'
            display_name: vision_fc_vc_01
            gateway_key: DRG-HUB-KEY
            provider_service_key: VISION-FC-VC-01-EQUINIX-FABRIC-KEY
            provision_fc_virtual_circuit: true
            show_available_fc_virtual_circuit_providers: false
            type: PRIVATE
      vcns:
        VCN-HUB-KEY:
          block_nat_traffic: false
          cidr_blocks:
          - 10.0.0.0/24
          default-security-list:
            egress_rules:
            - description: egress to 0.0.0.0/0 over ALL protocols
              dst: 0.0.0.0/0
              dst_type: CIDR_BLOCK
              protocol: ALL
              stateless: false
            ingress_rules:
            - description: ingress from 0.0.0.0/0 over TCP22
              dst_port_max: 22
              dst_port_min: 22
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
            - description: ingress from 0.0.0.0/0 over TCP443
              dst_port_max: 443
              dst_port_min: 443
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
          display_name: VCN-Hub
          dns_label: vcnhub
          is_attach_drg: false
          is_create_igw: false
          is_ipv6enabled: false
          is_oracle_gua_allocation_enabled: false
          route_tables:
            # Callout 5 - Traffic leaving Subnet H
            # Subnet Egress Route Table
            SUBNET-H-RT-KEY:
              display_name: subnet-h-rt
              route_rules:
                TO-ON-PREMISES-KEY:
                  description: Route for accessing the on-premises environment through
                    the DRG
                  destination: 172.16.0.0/16
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-A-KEY:
                  description: Route for accessing VCN-A through the DRG
                  destination: 192.168.10.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-B-KEY:
                  description: Route for accessing VCN-B through the DRG
                  destination: 192.168.20.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-C-KEY:
                  description: Route for accessing VCN-c through the DRG
                  destination: 192.168.30.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
            # Ingress Routes table - from DRGA-VCN-HUB to HUB-VCN
            # To be attahed to the VCN-HUB-DRG-Attachment
            # Sending all traffic that enters the HUB VCN, from the DRG, to the NFW for N-S and E-W inspection
            # You need this Route table only if you have a FW(Native or 3rd party) in the HUB-VCN for N-S and E-W traffic inspection
            VCN-H-INGRESS-RT-KEY:
              display_name: vcn-h-ingress-rt
              # The route rules bellow will be provisioned in 2 steps:
              #    - STEP 1: Run the configuration with no route rules in this route table
              #    - STEP 2: After STEP 1 run succesfully, copy the private_ip OCID of the NFW from the STEP 1 output, and use that to replace the content 
              #              of network_entity_id for all the 4 route rules bellow.   
              route_rules: null
              # ON-PREMISES-TO-NFW-PrivateIP-KEY:
              #    description: Route for fwd-ing traffic that has as destination the on-premises through the NFW
              #    destination: 172.16.0.0/16
              #    destination_type: CIDR_BLOCK
              #    network_entity_id: ocid1.privateip.oc1.eu-frankfurt-1.abtheljslfg2wxowcvsuwgu3oktsgokbzfmg5o6bbhpdduu465ups4pameqq
              #  VCN-A-TO-NFW-PrivateIP-KEY:
              #    description: Route for fwd-ing traffic that has as destination the VCN-A through the NFW
              #    destination: 192.168.10.0/24
              #    destination_type: CIDR_BLOCK
              #    network_entity_id: ocid1.privateip.oc1.eu-frankfurt-1.abtheljslfg2wxowcvsuwgu3oktsgokbzfmg5o6bbhpdduu465ups4pameqq
              #  VCN-B-TO-NFW-PrivateIP-KEY:
              #    description: Route for fwd-ing traffic that has as destination the VCN-A through the NFW
              #    destination: 192.168.20.0/24
              #    destination_type: CIDR_BLOCK
              #    network_entity_id: ocid1.privateip.oc1.eu-frankfurt-1.abtheljslfg2wxowcvsuwgu3oktsgokbzfmg5o6bbhpdduu465ups4pameqq
              #  VCN-C-TO-NFW-PrivateIP-KEY:
              #    description: Route for fwd-ing traffic that has as destination the VCN-A through the NFW
              #    destination: 192.168.30.0/24
              #    destination_type: CIDR_BLOCK
              #    network_entity_id: ocid1.privateip.oc1.eu-frankfurt-1.abtheljslfg2wxowcvsuwgu3oktsgokbzfmg5o6bbhpdduu465ups4pameqq
          subnets:
            SUBNET-H-KEY:
              cidr_block: 10.0.0.0/24
              dhcp_options_key: default_dhcp_options
              display_name: subneth-vcn-h
              dns_label: subnethvcnh
              ipv6cidr_blocks: []
              prohibit_internet_ingress: true
              prohibit_public_ip_on_vnic: true
              # Callout 5 - Traffic leaving Subnet H
              # Subnet Egress Route Table
              route_table_key: SUBNET-H-RT-KEY
              security_list_keys:
              - default_security_list
    SPOKES:
      category_freeform_tags:
        vision-sub-environment: spokes
      vcns:
        VCN-A-KEY:
          block_nat_traffic: false
          cidr_blocks:
          - 192.168.10.0/24
          default-security-list:
            egress_rules:
            - description: egress to 0.0.0.0/0 over ALL protocols
              dst: 0.0.0.0/0
              dst_type: CIDR_BLOCK
              protocol: ALL
              stateless: false
            ingress_rules:
            - description: ingress from 0.0.0.0/0 over TCP22
              dst_port_max: 22
              dst_port_min: 22
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
            - description: ingress from 0.0.0.0/0 over TCP443
              dst_port_max: 443
              dst_port_min: 443
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
          display_name: VCN-A
          dns_label: vcna
          is_attach_drg: false
          is_create_igw: false
          is_ipv6enabled: false
          is_oracle_gua_allocation_enabled: false
          route_tables:
            # Callout 3 - Traffic leaving Subnet 1
            SUBNET-1-RT-KEY:
              display_name: subnet-1-rt
              route_rules:
                TO-ON-PREMISES-KEY:
                  description: Route for accessing the on-premises environment through
                    the DRG
                  destination: 172.16.0.0/16
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-B-KEY:
                  description: Route for accessing VCN-B through the DRG
                  destination: 192.168.20.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-C-KEY:
                  description: Route for accessing VCN-c through the DRG
                  destination: 192.168.30.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
          subnets:
            SUBNET-1-KEY:
              cidr_block: 192.168.10.0/24
              dhcp_options_key: default_dhcp_options
              display_name: subnet1
              dns_label: subnet1
              ipv6cidr_blocks: []
              prohibit_internet_ingress: true
              prohibit_public_ip_on_vnic: true
              # Callout 3 - Traffic leaving Subnet 1
              route_table_key: SUBNET-1-RT-KEY
              security_list_keys:
              - default_security_list
        VCN-B-KEY:
          block_nat_traffic: false
          cidr_blocks:
          - 192.168.20.0/24
          default-security-list:
            egress_rules:
            - description: egress to 0.0.0.0/0 over ALL protocols
              dst: 0.0.0.0/0
              dst_type: CIDR_BLOCK
              protocol: ALL
              stateless: false
            ingress_rules:
            - description: ingress from 0.0.0.0/0 over TCP22
              dst_port_max: 22
              dst_port_min: 22
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
            - description: ingress from 0.0.0.0/0 over TCP443
              dst_port_max: 443
              dst_port_min: 443
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
          display_name: VCN-B
          dns_label: vcnb
          is_attach_drg: false
          is_create_igw: false
          is_ipv6enabled: false
          is_oracle_gua_allocation_enabled: false
          route_tables:
          # Callout 6 - Traffic leaving Subnet 2
            SUBNET-2-RT-KEY:
              display_name: subnet-2-rt
              route_rules:
                TO-ON-PREMISES-KEY:
                  description: Route for accessing the on-premises environment through
                    the DRG
                  destination: 172.16.0.0/16
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-A-KEY:
                  description: Route for accessing VCN-A through the DRG
                  destination: 192.168.10.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-C-KEY:
                  description: Route for accessing VCN-c through the DRG
                  destination: 192.168.30.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
          subnets:
            SUBNET-2-KEY:
              cidr_block: 192.168.20.0/24
              dhcp_options_key: default_dhcp_options
              display_name: subnet2
              dns_label: subnet2
              ipv6cidr_blocks: []
              prohibit_internet_ingress: true
              prohibit_public_ip_on_vnic: true
              # Callout 6 - Traffic leaving Subnet 2
              route_table_key: SUBNET-2-RT-KEY
              security_list_keys:
              - default_security_list
        VCN-C-KEY:
          block_nat_traffic: false
          cidr_blocks:
          - 192.168.30.0/24
          default-security-list:
            egress_rules:
            - description: egress to 0.0.0.0/0 over ALL protocols
              dst: 0.0.0.0/0
              dst_type: CIDR_BLOCK
              protocol: ALL
              stateless: false
            ingress_rules:
            - description: ingress from 0.0.0.0/0 over TCP22
              dst_port_max: 22
              dst_port_min: 22
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
            - description: ingress from 0.0.0.0/0 over TCP443
              dst_port_max: 443
              dst_port_min: 443
              protocol: TCP
              src: 0.0.0.0/0
              src_type: CIDR_BLOCK
              stateless: false
          display_name: VCN-C
          dns_label: vcnc
          is_attach_drg: false
          is_create_igw: false
          is_ipv6enabled: false
          is_oracle_gua_allocation_enabled: false
          route_tables:
            # Callout 7 - Traffic leaving Subnet 3
            SUBNET-3-RT-KEY:
              display_name: subnet-3-rt
              route_rules:
                TO-ON-PREMISES-KEY:
                  description: Route for accessing the on-premises environment through
                    the DRG
                  destination: 172.16.0.0/16
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-A-KEY:
                  description: Route for accessing VCN-A through the DRG
                  destination: 192.168.10.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
                TO-VCN-C-KEY:
                  description: Route for accessing VCN-B through the DRG
                  destination: 192.168.20.0/24
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-HUB-KEY
          subnets:
            SUBNET-3-KEY:
              cidr_block: 192.168.30.0/24
              dhcp_options_key: default_dhcp_options
              display_name: subnet3
              dns_label: subnet3
              ipv6cidr_blocks: []
              prohibit_internet_ingress: true
              prohibit_public_ip_on_vnic: true
              # Callout 7 - Traffic leaving Subnet 3
              route_table_key: SUBNET-3-RT-KEY
              security_list_keys:
              - default_security_list